# Generated by Django 4.2.5 on 2023-10-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('symb', models.ImageField(upload_to='')),
                ('year', models.DateField()),
            ],
            options={
                'db_table': 'contender_table',
            },
        ),
    ]
