# Generated by Django 4.2.5 on 2023-10-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_contender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contender',
            name='country',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contender',
            name='zip',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
