# Generated by Django 4.2.5 on 2023-10-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_contender_country_contender_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='votervotemapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'votervote_table',
            },
        ),
    ]
