# Generated by Django 4.2.5 on 2023-10-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_votervotemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhar',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='aadhar',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
