# Generated by Django 4.2.5 on 2023-10-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_aadhar_voter_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhar',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='aadhar',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
