# Generated by Django 4.2.5 on 2023-10-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_aadhar_alter_voter_aadhar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votervotemapping',
            name='name',
        ),
    ]
