# Generated by Django 4.2.5 on 2023-10-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_votervotemapping_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cbn', models.IntegerField()),
                ('Pk', models.IntegerField()),
                ('Jgn', models.IntegerField()),
            ],
            options={
                'db_table': 'count_table',
            },
        ),
    ]
