# Generated by Django 4.2.5 on 2023-10-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='Cbn',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='count',
            old_name='Jgn',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='count',
            name='Pk',
        ),
    ]
