# Generated by Django 4.2.5 on 2023-10-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_rename_cbn_count_count_rename_jgn_count_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
