# Generated by Django 4.2.5 on 2023-10-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_count_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
